# modified from: https://github.com/bevyengine/bevy/blob/main/.github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-unused-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@v1.0.0
      # We don't --force install to reduce CI times (drastically)
      # We fix the version so that it overwrites when we specify a new one
      # We need to remember to update the version from time to time
      - name: Installs cargo-udeps
        run: cargo install cargo-udeps@0.1.35
        # Cargo gives an error if it's already installed
        continue-on-error: true
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Run cargo udeps
        run: cargo +nightly udeps
