# modified from: https://github.com/bevyengine/bevy/blob/main/.github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-udeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Create cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target/
          # Update the cache every time the `Cargo.lock` file changes (i.e., the dependencies change).
          # We also include the `Cargo.toml` files in the hash in case the compile configurations change.
          key: 2-${{ runner.os }}-${{ inputs.cache-group }}-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          # Restore caches from the same group.
          restore-keys: |
            2-${{ runner.os }}-${{ inputs.cache-group }}-${{ hashFiles('**/Cargo.toml') }}-
             2-${{ runner.os }}-${{ inputs.cache-group }}-
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Installs cargo-udeps
        run: cargo install cargo-udeps@0.1.35
        # Cargo gives an error if it's already installed
        continue-on-error: true
      - name: Cargo udeps 1
        env:
          CARGO_LOG: cargo::core::compiler::fingerprint=info
        run: cargo udeps --verbose
      - name: Cargo udeps 2 --verbose
        env:
          CARGO_LOG: cargo::core::compiler::fingerprint=info
        run: cargo udeps
