# modified from: https://github.com/bevyengine/bevy/blob/main/.github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-udeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Cache normal Cargo build files
        uses: Leafwing-Studios/cargo-cache@fb29e934831d50f5a889865b9096ed5754140b8e
        with:
          cache-group: ${{ github.job }}-normal
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Installs cargo-udeps
        run: cargo install cargo-udeps@0.1.35
        # Cargo gives an error if it's already installed
        continue-on-error: true
      - name: Cache udeps Cargo build files
        uses: Leafwing-Studios/cargo-cache@fb29e934831d50f5a889865b9096ed5754140b8e
        with:
          cache-group: ${{ github.job }}-udeps
          cargo-home: ~/.cargo-udeps
          cargo-target-dir: target-udeps
      - name: Cargo udeps 1
        env:
          CARGO_LOG: cargo::core::compiler::fingerprint=info
          CARGO_HOME: ~/.cargo-udeps
          CARGO_TARGET_DIR: target-udeps
        run: cargo udeps --verbose
      - name: Cargo udeps 2
        env:
          CARGO_LOG: cargo::core::compiler::fingerprint=info
          CARGO_HOME: ~/.cargo-udeps
          CARGO_TARGET_DIR: target-udeps
        run: cargo udeps --verbose
